-- PrismBench Q1–Q8 (frozen for v1). Catalog: bench/queries.json
--
--   go run ./cmd/prism bench --scale testdata --repeat 3
--   go run ./cmd/prism sql --data-dir testdata/tables --file testdata/sql/ok/q1.sql
--
-- Individual files live in testdata/sql/ok/q1.sql … q8.sql plus q8_wide.sql.
